/* Copyright (C) 2023 Harry Clark */

/* Mario Kart Wii Discord Rich Presence */

/* THIS FILE PERTAINS TO AND APPLIES THE FUNCTIONALTY FOR READING */
/* THE CONTENTS OF THE DISK */

#include "dvd.h"

/* CONSTRUCTOR FOR THE DVD ARCHIVE */
/* REFERING TO ALL OF THE NECESSARY FUNCTIONS FOR THE BEGINNING */
/* OF THE PROGRAMS EXECUTION */

static inline DVD_ARCHIVE* DVD_CONSTRUCTOR()
{
	MULTI_DVD* MULTI_DVD_ARCHIVE = nullptr;
	DVD_ARCHIVE_START();
	ARCHIVE_FUNCTIONS::ARCHIVE_SIZE* ARCHIVE_SIZE = 0;
	ARCHIVE_FUNCTIONS::ARCHIVE_HEAP* ARCHIVE_HEAP = nullptr;
	DVD_FILE_START();
	ARCHIVE_FUNCTIONS::FILE_SIZE* FILE_SIZE = 0;
	ARCHIVE_FUNCTIONS::FILE_HEAP* FILE_HEAP = nullptr;
	DVD_STATE DVD_STATUS = DVD_STATE::CLEARED;
}

/* DECLARE WHEN THE DVD HAS BEEN INITIALISED AND MOUNTED */
/* INTO THE HEAP */

static void DVD_MOUNT(HEAP* ARCHIVE_HEAP)
{
	DVD_ARCHIVE_START();
	DVD_STATE DVD_STATUS = DVD_STATE::MOUNTED;
}

/* LOAD THE CONTENTS OF THE PROVIDED DVD DISK IMAGE */
/* INTO THE HEAP AND STACK OF THE PROGRAM */

/* THIS IS POSSIBLE BY DETERMINING THE ALLOCATED DIRECTION OF */
/* THE DIRECTION POINTER WHICH READS AND WRITES THE CONTENTS TO THE HEAP */

static void DVD_LOAD(const char* PATH, HEAP* FILE_HEAP, HEAP* ARCHIVE_HEAP, bool COMPRESSED, bool RIPPED, S8* ALIGNMENT)
{
	if (!COMPRESSED || !FILE_HEAP) FILE_HEAP = ARCHIVE_HEAP;

	if (DVD_STATE::CLEARED)
	{
		RIPPED = false;
		DVD_RIPPER_ALLOC::ALLOC_NEG;

		if (COMPRESSED == false) ALIGNMENT++;
		if (ALIGNMENT < 0) DVD_RIPPER_ALLOC::ALLOC_POS;
	}
}

/* LOAD THE CORRESPONDING FILE BUFFER TAKING INTO ACCOUNT THE FILE SIZE */
/* DECOMPRESS THOSE CONTENTS THROUGH THE DVD HEAP */
/* UPON DECOMPRESSING THE CONTENTS, ADD THEM TO THE HEAP */

static void DVD_LOAD_BUFFER(void* FILE_START, U32* FILE_SIZE, HEAP* ARCHIVE_HEAP, S32 DECOMP)
{
	ARCHIVE_FUNCTIONS::FILE_SIZE FILE_SIZE = FILE_SIZE;
	if (DECOMP != 0)
	{
		DVD_ARCHIVE::DECOMP(ARCHIVE_HEAP);
		ARCHIVE_FUNCTIONS::FILE_SIZE FILE_SIZE = 0;
		ARCHIVE_FUNCTIONS::FILE_HEAP FILE_HEAP = 0;
	}

	DVD_ARCHIVE::MOUNT(ARCHIVE_HEAP);
}