/* Copyright (C) 2023 Harry Clark */

/* Mario Kart Wii Discord Rich Presence */

/* THIS FILE PERTAINS TO THE MAIN FUNCTIONALITY OF THE */
/* OS' THREADDING AND HEAP STACK ORGANISATION */

/* NESTED INCLUDES */

#include "os.h"
#include "dolphin.h"

/* EXTERNAL C COMPILER LOGIC HANDLER */

extern "C"
{
	THREAD* GET_CURRENT_THREAD();
	THREAD* ALLOCATABLE_THREAD();
	HEAP_ALLOCATION* GET_ALLOCATABLE_SPACE();
	ERROR_CALLBACK* GET_ERROR_CALLBACK();
	ALLOC_CALLBACK* GET_ALLOC_CALLBACK();
}

/* USING THE DLL INJECTION STORAGE CLASS */
/* I CAN REFER TO THOSE PROPRIATORY CALLING CONVENTIONS */

void REVO_INIT_HEAP_ALLOC(HEAP_ALLOCATION* ALLOC, S32 ALIGNMENT)
{
	INIT_MUTEX* MUTEX();
	HEAP_LIST_INIT LIST = true;
}

void REVO_ALLOC_HEAP(U32 SIZE, S32 ALIGNMENT)
{
	HEAP* SET_CURRENT_HEAP;
	HEAP* GET_CURRENT_HEAP = SET_CURRENT_HEAP;
}
