/* Copyright (C) 2023 Harry Clark */

/* Mario Kart Wii DIscord Rich Presence */

/* THIS FILE PERTAINS TO THE FUNCTIONALITY OF THE DOLPHIN */
/* EMULATOR; PROVIDING CLARITY AND DECLARATIONS FOR FUNCTIONS */
/* THAT THE DLL INJECT WILL LOOK OUT FOR */

#ifndef DOLPHIN
#define DOLPHIN

/* NESTED INCLUDES */

#include "common.h"

/* NESTED INCLUDES */

#include <iosfwd>
#include <process.h>
#include <stdio.h>
#include <thread>

/* USING THE C CONVENTION CALL SCHEMA */
/* I CAN DYNAMICALLY LOAD THE PROGRAM */
/* PROVIDED THAT THE ARGS HAVE BEEN SATISFIED */

#define EMUALAION_MEM_SIZE 0x2000000
#define EMUALTION_MEM_BASE 0x80000000

/* WE CALL THE DECLSPEC STORAGE CLASS */
/* TO CREATE THE COROUTINES FOR THE DLL INJECTION */

extern DECLSPEC U32 REVO_CALL REVO_INIT(U32 FLAGS);
extern DECLSPEC U32 REVO_CALL REVO_SUSPEND(void);

#ifndef PROCESS_MEMORY
#define PROCESS_MEMORY

#ifndef WIN_32_LEAN_AND_MEAN
#define WIN_32_LEAN_AND_MEAN
#include <Windows.h>

static HANDLE CURRENT_PROCESS;

#endif

#define FUNCTION_POINTER(NAME, RETURN_TYPE, ARGS, ADDRESS) \
static RETURN_TYPE(REVO_CALL* NAME) ARGS = RETURN_TYPE(REVO_CALL *ARGS()ADDRESS);

#define UNKWOWN_POINTER(...)(__VA_ARGS__)

#define VOID_FUNCTION(NAME, ADDRESS) \
FUNCTION_POINTER(void NAME, void ADDRESS);

#define DATA_POINTER(NAME, TYPE, ADDRESS) \
static TYPE &NAME = (*TYPE)&ADDRESS;

#define DATA_ARRAY(NAME, TPYE, ADDRESS, LENGTH) \
static TYPE *const NAME = (*TYPE)&ADDRESS;

static inline BOOL WRITE_DATA(void *ADDRESS, const char DATA, UNK* BYTES)
{
	typedef U32 RESULT;
	RESULT GET_RESULT = WRITE_DATA(ADDRESS, DATA, NULL);
	return GET_RESULT;
}

#endif

#endif
