/* Copyright (C) 2023 Harry Clark */

/* Mario Kart Wii Discord Rich Presence */

/* THIS FILE PERTAINS TO THE FUNCTIONALITY OF THE DVD */
/* STRUCTURE IN RELATION TO THE FUINCTIONALITY OF THE OS */

/* THIS IS TO FURTHER UNDERSTAND THE VARIOUS STATES OF THE */
/* DVD'S READ AND WRITE PROCESS */

#ifndef DVD
#define DVD

/* NESTED INCLUDES */

#include "common.h"
#include "dolphin.h"
#include "os.h"

typedef enum DVD_STATE
{
	CLEARED = 0,
	RIPPED = 1,
	DECOMP = 2,
	MOUNTED = 3,
};

typedef struct DVD_ARCHIVE{};
typedef struct MULTI_DVD : DVD_ARCHIVE{};
typedef struct RESOURCE_MANAGER : DVD_ARCHIVE{};

/* SPLIT UP THE DVD'S FUNCTIONS INDEPENDANTLY FROM THE STRUCTURE */
/* TO MAKE EFFECTIVE AND MORE CONCISE USE OF THE CALLING CONVENTION */

/* WITH SAVE ME HAVING TO WORRY TOO MUCH ABOUT TYPE DECLARATION */
/* FOR THESE OBJECTS */

/* THE STRUCTURES WILL STILL BE HERE TO CORRESPOND WITH THE POINTING */
/* AND REFERNCING OF INSTANCES THROUGHOUT THE PROGRAM */

VOID_FUNCTION(DVD_MOUNT);
VOID_FUNCTION(DVD_LOAD);
VOID_FUNCTION(DVD_LOAD_UNUSED);
VOID_FUNCTION(DVD_LOAD_BUFFER);
VOID_FUNCTION(DVD_CLEAR);
VOID_FUNCTION(DVD_UNMOUNT);
VOID_FUNCTION(DVD_GET_ARCHIVE_END);
VOID_FUNCTION(DVD_ARCHIVE_START);
VOID_FUNCTION(DVD_FILE_START);

typedef struct ARCHIVE_FUNCTIONS
{
	typedef U32* ARCHIVE_SIZE;
	typedef U32* FILE_SIZE;
	typedef HEAP* ARCHIVE_HEAP;
	typedef HEAP* FILE_HEAP;
	DVD_STATE DVD_STATUS;
};

#endif
