/* Copyright (C) 2023 Harry Clark */

/* Mario Kart Wii Discord Rich Presence */

/* THIS FILE PERTAINS TO THE FUNCTIONALITY OF THE DVD */
/* STRUCTURE IN RELATION TO THE FUINCTIONALITY OF THE OS */

/* THIS IS TO FURTHER UNDERSTAND THE VARIOUS STATES OF THE */
/* DVD'S READ AND WRITE PROCESS */

#ifndef DVD
#define DVD

/* NESTED INCLUDES */

#include "common.h"
#include "dolphin.h"
#include "os.h"

typedef enum DVD_STATE
{
	CLEARED = 0,
	RIPPED = 1,
	DECOMP = 2,
	MOUNTED = 3,
};

typedef struct DVD_ARCHIVE
{
	typedef void(*DECOMP)(void);
	typedef void(*MOUNT)(void);
};

typedef struct MULTI_DVD : DVD_ARCHIVE{};
typedef struct RESOURCE_MANAGER : DVD_ARCHIVE{};

typedef struct ARCHIVE_FUNCTIONS
{
	typedef U32* ARCHIVE_SIZE;
	typedef U32* FILE_SIZE;
	typedef HEAP* ARCHIVE_HEAP;
	typedef HEAP* FILE_HEAP;
};

/* METHODS FOR DETERMINING THE CONTENTS OF THE FILE */
/* IN QUESTION, BY PROVIDING METHODS TO THE ARCHIVE TO READ AND WRITE */

typedef struct DVD_FILE
{
	typedef void(*INITIALISE(void));
	typedef bool OPEN_FILE(const char* PATH);
	typedef void(*CLOSE(void));

	typedef S32 READ_DVD_DATA(void* BUFFER, S32* LENGTH, S32* OFFSET);
	typedef S32 WRITE_DVD_DATA(void* BUFFER, S32* LENGTH, S32* OFFSET);
	typedef U32 FILE_SIZE() const;

};

typedef struct DVD_FILE_INFO : DVD_FILE
{
	DVD_FILE_INFO* GET_FILE_INFO();
	DVD_FILE* DVD_FILE;
};

/* METHODS TO CONSTRUCT THE MEANS OF RIPPING THE CONTENTS OF THE FILE */

typedef struct DVD_RIPPER
{
	typedef void(*DVD_CALLBACK)(void);
	typedef bool RIP_ERROR;

	typedef U8* ALLOC_PATH(const char* PATH, HEAP* HEAP, DVD_RIPPER_ALLOC* ALLOC_DIR, U32 OFFSET, U32 FILE_SIZE);
	static U8* ALLOC_PATH_TO_RAM(ALLOC_PATH* PATH, DVD_FILE* DVD_FILE, U8* DESTINATION);
	static U8* DECOMP_RAM_ALLOC(ALLOC_PATH* PATH, U32* MAX_CHUNK_SIZE);
};

typedef enum DVD_RIPPER_ALLOC
{
	ALLOC_NEG, // ALLOC FROM TOP OF THE BLOCK
	ALLOC_POS, // ALLOC FROM BOTTOM OF THE BLOCK
	ALLOC_UNK
};

/* SPLIT UP THE DVD'S FUNCTIONS INDEPENDANTLY FROM THE STRUCTURE */
/* TO MAKE EFFECTIVE AND MORE CONCISE USE OF THE CALLING CONVENTION */

/* WITH SAVE ME HAVING TO WORRY TOO MUCH ABOUT TYPE DECLARATION */
/* FOR THESE OBJECTS */

/* THE STRUCTURES WILL STILL BE HERE TO CORRESPOND WITH THE POINTING */
/* AND REFERNCING OF INSTANCES THROUGHOUT THE PROGRAM */

VOID_FUNCTION(DVD_MOUNT);
VOID_FUNCTION(DVD_LOAD);
VOID_FUNCTION(DVD_LOAD_UNUSED);
VOID_FUNCTION(DVD_LOAD_BUFFER);
VOID_FUNCTION(DVD_CLEAR);
VOID_FUNCTION(DVD_UNMOUNT);
VOID_FUNCTION(DVD_GET_ARCHIVE_END);
VOID_FUNCTION(DVD_ARCHIVE_START);
VOID_FUNCTION(DVD_FILE_START);

#endif
