/* Copyright (C) 2023 Harry Clark */

/* Mario Kart Wii DIscord Rich Presence */

/* THIS FILE PERTAINS TO THE FUNCTIONALITY OF THE WII'S OS */
/* DISCERNING HOW THREADDING WORKS TO PARSE INFORMATION */
/* TO DETERMINE WHAT THE OS SHOULD BE READING AND WRITING FROM */

/* THIS IS MORE SO JUST TO OUTLINE THE WII'S HEAP AND STACK SCHEMA */
/* TO WRITE AND READ SAID MEMORY PROPERLY */

#ifndef OS_THREADDING
#define OS_THREADDING

/* NESTED INCLUDES */

#include "common.h"
#include "dolphin.h"

#define OS_BUS_CLOCK 0x800000F8
#define OS_TIMER_CLOCK (OS_BUS_CLOCK >> 2)
#define OS_SLEEP 5000
#define OS_MSEC 
#define OS_SECONDS_TO_TICK() ((OS_MSEC * (OS_TIMER_CLOCK) / 1000))
#define OS_SLEEP_TICK() (OS_MSEC)

typedef struct THREAD
{
	CHAR* STACK_LOW;
	CHAR* STACK_HIGH;
	U32* OS_ERROR;
};

typedef struct THREAD_QUEUE
{
	THREAD* HEAD;
	THREAD* TAIL;
};

/* CREATE THE OS THREADDING COROUTINE USING THE DLL INJECTION STORAGE CLASS */

extern DECLSPEC U32 REVO_CALL REVO_CREATE_THREAD(THREAD* THREAD, 
	void* CALLBACK(void)), void* STACK(void);

extern DECLSPEC S32 REVO_CALL REVO_RESUME_THREAD(THREAD* THREAD);
extern DECLSPEC U32 REVO_CALL REVO_TERMINATE(THREAD* THREAD);
extern DECLSPEC void REVO_CALL REVO_CANCEL_THREAD(THREAD* THREAD);
extern DECLSPEC void REVO_CALL REVO_DETATCH_THREAD(THREAD* THREAD);
extern DECLSPEC THREAD* REVO_CALL REVO_GET_CURRENT_THREAD();

/* UNKNOWN AND VOID FUNCTION DECLARATIES FOR MISC. FUNCTIONS */
/* PERTAINING TO THE THREADDING COROUTINE */

VOID_FUNCTION(OS_INIT_THREAD_QUEUE);
UNKNOWN_FUNCTION(OS_THREAD_INIT);
UNKNOWN_FUNCTION(OS_UNSET);
UNKNOWN_FUNCTION(OS_SELECT_THREAD);
UNKNOWN_FUNCTION(OS_EXIT_THREAD);
UNKNOWN_FUNCTION(OS_JOIN_THREAD);
UNKNOWN_FUNCTION(OS_SUSPEND_THREAD);


#endif
