/* Copyright (C) 2023 Harry Clark */

/* Mario Kart Wii DIscord Rich Presence */

/* THIS FILE PERTAINS TO THE FUNCTIONALITY OF THE WII'S OS */
/* DISCERNING HOW THREADDING WORKS TO PARSE INFORMATION */
/* TO DETERMINE WHAT THE OS SHOULD BE READING AND WRITING FROM */

#ifndef OS_THREADDING
#define OS_THREADDING

/* NESTED INCLUDES */

#include "common.h"
#include "dolphin.h"

#define OS_BUS_CLOCK 0x800000F8
#define OS_TIMER_CLOCK (OS_BUS_CLOCK >> 2)

typedef struct THREAD{};

typedef struct THREAD_QUEUE
{
	THREAD* HEAD;
	THREAD* TAIL;
};


VOID_FUNCTION(OS_INIT_THREAD_QUEUE, THREAD_QUEUE);
UNKNOWN_FUNCTION(OS_THREAD_INIT);
UNKNOWN_FUNCTION(OS_UNSET);
UNKNOWN_FUNCTION(OS_SELECT_THREAD);
UNKNOWN_FUNCTION(OS_EXIT_THREAD);
UNKNOWN_FUNCTION(OS_JOIN_THREAD);
UNKNOWN_FUNCTION(OS_SUSPEND_THREAD);


#endif