/* Copyright (C) 2023 Harry Clark */

/* Mario Kart Wii DIscord Rich Presence */

/* THIS FILE PERTAINS TO THE FUNCTIONALITY OF THE WII'S OS */
/* DISCERNING HOW THREADDING WORKS TO PARSE INFORMATION */
/* TO DETERMINE WHAT THE OS SHOULD BE READING AND WRITING FROM */

/* THIS IS MORE SO JUST TO OUTLINE THE WII'S HEAP AND STACK SCHEMA */
/* TO WRITE AND READ SAID MEMORY PROPERLY */

#ifndef OS_THREADDING
#define OS_THREADDING

/* NESTED INCLUDES */

#include "common.h"
#include "dolphin.h"

#define OS_BUS_CLOCK 0x800000F8
#define OS_TIMER_CLOCK (OS_BUS_CLOCK >> 2)
#define OS_SLEEP 5000
#define OS_MSEC 
#define OS_SECONDS_TO_TICK() ((OS_MSEC * (OS_TIMER_CLOCK) / 1000))
#define OS_SLEEP_TICK() (OS_MSEC)

typedef struct THREAD
{
	CHAR* STACK_LOW;
	CHAR* STACK_HIGH;
	U32* OS_ERROR;
};

typedef struct THREAD_QUEUE
{
	THREAD* HEAD;
	THREAD* TAIL;
};

typedef struct OS_MUTEX
{
	CHAR MUTEX[0x18];
};

typedef void(*INIT_MUTEX);
typedef void(*LOCK_MUTEX);
typedef void(*UNLOCK_MUTEX);

/* REWRITE OF MKW'S EGG LIBRARY */
/* USED FOR HEAP AND STACK FUNCTIONALITY WITH */
/* OTHER EXTERNAL LIBS SUCH AS MATH AND GRAPHICS */

#ifndef EGG_HEAP
#define EGG_HEAP

#define ENTRY_SIZE(TYPE, VALUE, SIZE)
static ENTRY_SIZE(U32* ITERATION(&U32 ENTRIES[0]));

#define ADD_SIZE(GROUP, SIZE)
static ADD_SIZE(U16* GROUP_ID, U32* SIZE);

#define RESET() void RESET(void)
static RESET(void);

/* CREATE HEAP ALLOCATION DECLARATIVES USING THE */
/* DLL INJECTION STORAGE CLASS */

extern DECLSPEC void REVO_CALL REVO_INIT_HEAP_ALLOC(HEAP_ALLOCATION* ALLOC, S32 ALIGNMENT = 0);
extern DECLSPEC void REVO_CALL REVO_ALLOC_HEAP(U32 SIZE, S32 ALIGNMENT = 0);
extern DECLSPEC void REVO_CALL REVO_FREE_HEAP(void* HEAP_BLOCK);
extern DECLSPEC void REVO_CALL REVO_DESTROY_HEAP();
extern DECLSPEC U32 REVO_CALL REVO_ALLOC_SIZE(S32 ALIGNMENT = 0);
extern DECLSPEC U32 REVO_CALL REVO_RESIZE_BLOCK(U32 SIZE = 0);
extern DECLSPEC U32 REVO_CALL REVO_ADJUST_HEAP();

/* CREATE HEAP STRUCTURES */
/* HOUSES THE NECESSITIES FOR ALLOCATION */
/* AND THE ARGUMENT ASSOCIATED */

typedef struct HEAP
{
	/* JUST GOING OFF OF THE MKW DECOMP */

	typedef enum TYPE
	{
		NONE = 0,
		EXPAND,
		FRAME,
		UNIT
	};

	typedef bool GET_HEAP_EXPAND();
	typedef HEAP* GET_PARENT();
	typedef void(*GET_ADDRESS(void));

};

typedef struct EXP_HEAP : HEAP{};

/* DETERMINE THE SIZE OF THE ARG THROUGH */
/* HEX 0 TO 0C; 0 - 12 BITS */

typedef struct HEAP_ALLOCATION
{
	U32 ARG;
	U32 SIZE;
	U32 ALIGNMENT;
	typedef HEAP* ALLOC_HEAP;
};

typedef void(*ALLOC_CALLBACK(void));
typedef void(*ERROR_CALLBACK(void));
typedef bool HEAP_LIST_INIT;

#endif

/* CREATE THE OS THREADDING COROUTINE USING THE DLL INJECTION STORAGE CLASS */

extern DECLSPEC U32 REVO_CALL REVO_CREATE_THREAD(THREAD* THREAD, 
	void* CALLBACK(void)), void* STACK(void);

extern DECLSPEC S32 REVO_CALL REVO_RESUME_THREAD(THREAD* THREAD);
extern DECLSPEC U32 REVO_CALL REVO_TERMINATE(THREAD* THREAD);
extern DECLSPEC void REVO_CALL REVO_CANCEL_THREAD(THREAD* THREAD);
extern DECLSPEC void REVO_CALL REVO_DETATCH_THREAD(THREAD* THREAD);
extern DECLSPEC THREAD* REVO_CALL REVO_GET_CURRENT_THREAD();

/* UNKNOWN AND VOID FUNCTION DECLARATIES FOR MISC. FUNCTIONS */
/* PERTAINING TO THE THREADDING COROUTINE */

VOID_FUNCTION(OS_INIT_THREAD_QUEUE);
UNKNOWN_FUNCTION(OS_THREAD_INIT);
UNKNOWN_FUNCTION(OS_UNSET);
UNKNOWN_FUNCTION(OS_SELECT_THREAD);
UNKNOWN_FUNCTION(OS_EXIT_THREAD);
UNKNOWN_FUNCTION(OS_JOIN_THREAD);
UNKNOWN_FUNCTION(OS_SUSPEND_THREAD);
UNKNOWN_FUNCTION(OS_INIT_CONDITION);
UNKNOWN_FUNCTION(OS_SIGNAL_CONDITION);

#endif
