/* Copyright (C) 2023 Harry Clark */

/* Mario Kart Wii Discord Rich Presence */

/* THIS FILE PERTAINS TO THE DECLARATION OF THE FUNCTIONALITY */
/* FOR ACCESSING THE MEMORY ADDRESS OF THE RACE TRACKS */
/* AND ANY OTHER PRE-REQUISITES THAT MAY FOLLOW */

#ifndef RACE_CONFIG
#define RACE_CONFIG

/* NESTED INCLUDES */

#include "dvd.h"
#include "os.h"
#include "common.h"

extern DECLSPEC REVO_CALL S16 CHAR_ID_SLOT();
extern DECLSPEC REVO_CALL S16 COURSE_ID_SLOT();

#ifndef RACE_PARAMS
#define RACE_PARAMS

#define MAX_PLAYER 12
#define MAX_CHARACTERS 32
#define MAX_COURSES 32
#define COURSE_CACHE_STATE (0 << 3)
#define FILENAME
#define CHARACTER_NAME U8
#define COURSE_NAME U8

#endif

typedef enum CHARACTERS
{
	BABY_MARIO = 0x6,
	MINI_LUIGI = 0xC,
	BABY_PEACH = 0x1,
	BABY_DAISY = 0x4,
	TOAD = 0x8,
	TOADETTE = 0xD,
	KOOPA_TROOPA = 0xE,
	DRY_BONES = 0x5,

	MARIO = 0x0,
	LUIGI = 0x7,
	PEACH = 0x10,
	DAISY = 0xF,
	YOSHI = 0xA,
	BIRDO = 0x11,
	DIDDY_KONG = 0x12,
	BOWSER_JR = 0x14,

	WARIO = 0xB,
	WALUIGI = 0x2,
	DONKEY_KONG = 0x9,
	BOWSER = 0x3,
	KING_BOO = 0x13,
	ROSALINA = 0x17,
	FUNKY_KONG = 0x16,
	DRY_BOWSER = 0x15
};

typedef enum COURSES
{
	MARIO_CIRCUIT = 0x0,
	MOO_MOO_MEADOWS = 0x1,
	MUSHROOM_GORGE = 0x2,
	GRUMBLE_VOLCANO = 0x3,
	TOADS_FACTORY = 0x4,
	COCONUT_MALL = 0x5,
	DK_SUMMIT = 0x6, 
	WARIOS_GOLD_MINE = 0x7,
	LUIGI_CIRCUIT = 0x8,
	DAISY_CIRCUIT = 0x9,
	MOONVIEW_HIGHWAY = 0xA,
	MAPLE_TREEWAY = 0xB,
	BOWSERS_CASTLE = 0xC,
	RAINBOW_ROAD = 0xD,
	DRY_DRY_RUINS = 0xE,
	KOOPA_CAPE = 0xF,

	GCN_PEACH_BEACH = 0x10,
	GCN_MARIO_CIRCUIT = 0x11,
	GCN_WALUIGI_STADIUM = 0x12,
	GCN_DK_MOUNTAIN = 0x13,
	DS_YOSHI_FALLS = 0x14,
	DS_DESERT_HILLS = 0x15,
	DS_PEACH_GARDENS = 0x16,
	DS_DELFINO_SQUARE = 0x17,
	SNES_MARIO_CIRCUIT_3 = 0x18,
	SNES_GHOST_VALLEY_2 = 0x19,
	N64_MARIO_RACEWAY = 0x1A,
	N64_SHERBET_LAND = 0x1B,
	N64_BOWSERS_CASTLE = 0x1C,
	N64_DKS_JUNGLE_PARKWAY = 0x1D,
	GBA_BOWSER_CASTLE_3 = 0x1E,
	GBA_SHY_GUY_BEACH = 0x1F,
};

typedef struct RACE_CACHE
{
	typedef void(*CACHE_INIT)(void);
	typedef void(*CACHE_LOAD)(void);
	typedef void(*CACHE_FREE)(void);
	typedef void(*CACHE_LOAD_HEAP)(DVD_ARCHIVE* DVD_ARCHIVE, HEAP* HEAP);
	void(*CACHE_BUFFER)(void);
	void(*CACHE_BLOCK)(void);
};

/* ALLOCATE THE CONSTRUCTOR FOR THE COURSE RELATIVE */
/* TO HOW THE SYSTEM WILL PARSE THAT INFORMATION */

/* THE CONCEPT BEHIND THIS IS THAT FOR EVERY SCENE LOADED, THE PREVIOUS */
/* WILL GET LOADED ONTO THE HEAP READY TO BE RECYCLED OR DESTROYED */

typedef struct RACE_MANAGER
{
	static DVD_ARCHIVE* SCENE_ARCHIVE;
	static DVD_ARCHIVE* SYSTEM_ARCHIVE;

	typedef char* RACE_FILENAME;
	typedef U32 RACE_INDEX;
	typedef DVD_ARCHIVE* LOAD_COURSE(COURSES* COURSES);
	typedef DVD_ARCHIVE* LOAD_SYSTEM_RESOURCES();

	typedef bool(*SCENE_INIT)();
};

typedef struct CHARACTER_MANAGER
{
	typedef char* NAME(CHARACTERS* CHARACTERS);
	typedef char* LOAD_NAME;
};

VOID_FUNCTION(GET_CHARACTER_NAME);
VOID_FUNCTION(GET_COURSE_NAME);

#endif
