/* Copyright (C) 2023 Harry Clark */

/* Mario Kart Wii Discord Rich Presence */

/* THIS FILE PERTAINS TO THE DECLARATION OF THE FUNCTIONALITY */
/* FOR ACCESSING THE MEMORY ADDRESS OF THE RACE TRACKS */
/* AND ANY OTHER PRE-REQUISITES THAT MAY FOLLOW */

#ifndef RACE_CONFIG
#define RACE_CONFIG

/* NESTED INCLUDES */

#include "os.h"
#include "common.h"

/* EXTERNAL FUNCTION REFERENCING */
/* USED FOR ACCESSING THE WII'S HEAP AND STACK */
/* FOR THREADDING */

extern UNKNOWN_FUNCTION(OS_SUSPEND_THREAD);
extern DECLSPEC REVO_CALL S16 COURSE_ID_SLOT;

#ifndef RACE_PARAMS
#define RACE_PARAMS

#define MAX_PLAYER 12
#define COURSE_CACHE_STATE (0 << 3)

#define COURSE_FILE_NAME(VALUE) \
static DECLSPEC REVO_CALL COURSE_FILE(const char* FILENAME);

#endif

#endif
