/* Copyright (C) 2023 Harry Clark */

/* Mario Kart Wii Discord Rich Presence */

/* THIS FILE PERTAINS TO THE DECLARATION OF THE FUNCTIONALITY */
/* FOR ACCESSING THE MEMORY ADDRESS OF THE RACE TRACKS */
/* AND ANY OTHER PRE-REQUISITES THAT MAY FOLLOW */

#ifndef RACE_CONFIG
#define RACE_CONFIG

/* NESTED INCLUDES */

#include "dvd.h"
#include "os.h"
#include "common.h"

/* EXTERNAL FUNCTION REFERENCING */
/* USED FOR ACCESSING THE WII'S HEAP AND STACK */
/* FOR THREADDING */

extern UNKNOWN_FUNCTION(OS_SUSPEND_THREAD);
extern DECLSPEC REVO_CALL S16 COURSE_ID_SLOT;

#ifndef RACE_PARAMS
#define RACE_PARAMS

#define MAX_PLAYER 12
#define COURSE_CACHE_STATE (0 << 3)
#define MENU_STATE (0 << 3)

#define COURSE_FILE_NAME(VALUE, ID) \
static DECLSPEC REVO_CALL COURSE_FILE(const char* FILENAME, COURSE_ID_SLOT);

#endif

typedef enum CHARACTERS
{
	BABY_MARIO = 0x6,
	BABY_LUIGI = 0xC,
	BABY_PEACH = 0x1,
	BABY_DAISY = 0x4,
	TOAD = 0x8,
	TOADETTE = 0xD,
	KOOPA_TROOPA = 0xE,
	DRY_BONES = 0x5,

	MARIO = 0x0,
	LUIGI = 0x7,
	PEACH = 0x10,
	DAISY = 0xF,
	YOSHI = 0xA,
	BIRDO = 0x11,
	DIDDY_KONG = 0x12,
	BOWSER_JR = 0x14,

	WARIO = 0xB,
	WALUIGI = 0x2,
	DONKEY_KONG = 0x9,
	BOWSER = 0x3,
	KING_BOO = 0x13,
	ROSALINA = 0x17,
	FUNKY_KONG = 0x16,
	DRY_BOWSER = 0x15
};

typedef struct RACE_CACHE
{
	typedef void(*CACHE_INIT)(void);
	typedef void(*CACHE_LOAD)(void);
	typedef void(*CACHE_LOAD_HEAP)(DVD_ARCHIVE* DVD_ARCHIVE, HEAP* HEAP);
};

/* ALLOCATE THE CONSTRUCTOR FOR THE COURSE RELATIVE */
/* TO HOW THE SYSTEM WILL PARSE THAT INFORMATION */

/* THE CONCEPT BEHIND THIS IS THAT FOR EVERY SCENE LOADED, THE PREVIOUS */
/* WILL GET LOADED ONTO THE HEAP READY TO BE RECYCLED OR DESTROYED */

typedef struct RACE_MANAGER
{
	DVD_ARCHIVE* SCENE_ARCHIVE;
	DVD_ARCHIVE* SYSTEM_ARCHIVE;
	CHARACTER_MANAGER* CHARACTER_MANAGER[];
};

typedef struct CHARACTER_MANAGER
{
	typedef char* GET_NAME(CHARACTERS* CHARACTERS);
};

VOID_FUNCTION(GET_CHARACTER_NAME);
VOID_FUNCTION(GET_TRACK_NAME);
VOID_FUNCTION(GET_FILE);
STATIC_FUNCTION(DESTROY_COURSE_INSTANCE);

#endif
