/* Copyright (C) 2023 Harry Clark */

/* Mario Kart Wii Discord Rich Presence */

/* THIS FILE PERTAINS TO THE FUNCTIONALITY OF THE PREPRIATORY */
/* DISCORD HEADER FILE AS WELL AS THE FUNCTION FROM THE RACE FILE */
/* THAT DICTATES THE POINTER NOTATION TO THE TRACKS AND CHARACTERS */

/* NESTED INCLUDES */

#include "discord.h"
#include "race.h"

/* CREATE AN OBJECT TO INITIALISE THE CLIENT WHEN IT STARTS EXECUTION */
/* THIS IS BY CHECKING THE SIGNATURE SCAN OF THE INITIALISATION OF THE IOS */
/* THAT DETERMINES THE OPENING OF A .dol */

/* ALLOCATE MEMORY OF THE STACK FOR THE CONNECTION TO TAKE PLACE  */
/* SET THE CORRESPONDENCE ACCORDING TO THE ENUM SIZE */

static CONNECTION* INIT_CONNECTION(CONNECTION* CONNECT, DOL_IOS* IOS, IOS_RESULT* RESULT)
{
	if (!IOS->IOS_OPEN())
	{
		CONNECT += 1, sizeof(CONNECTION::UNSUPPORTED);
		return;
	}

	RESULT += sizeof(RESULT->DISCORD_SET(DISCORD_APP_ID));
}
