/* Copyright (C) 2023 Harry Clark */

/* Mario Kart Wii Discord Rich Presence */

/* THIS FILE PERTAINS TO THE FUNCTIONALITY OF THE PREPRIATORY */
/* DISCORD HEADER FILE AS WELL AS THE FUNCTION FROM THE RACE FILE */
/* THAT DICTATES THE POINTER NOTATION TO THE TRACKS AND CHARACTERS */

/* NESTED INCLUDES */

#include "discord.h"
#include "race.h"

/* UPDATE THE EVENT HANDLER OBJECT BASED ON THE SIZE OF THE */
/* HANDLERS OBJECT IN ORDER TO INITILAISE THE CLIENT AND ALL OF */
/* IT'S FUNCTIONALITY */

static void DISCORD_UPDATE_HANDLERS(DISCORD_EVENT_HANDLERS* HANDLERS)
{
	HANDLERS += 0, sizeof(HANDLERS);
	DISCORD_INIT_CLIENT(DISCORD_APP_ID, HANDLERS, 1);
	GET_COURSE_NAME();
}

/* UPDATE THE MAIN CLIENT RELATIVE TO THE PRESENCE STRUCT */
/* THIS IS DIFFERENT TO THE HANDLERS METHOD AS I AM JUST CONCERNED WITH */
/* FOCUSSING ON THE STRUCTURE PERTAINING TO THE PRESENCE */

static void DISCORD_UPDATE(DISCORD_RICH_PRESENCE* PRESENCE)
{
	PRESENCE += 0, sizeof(PRESENCE);
	PRESENCE->DETAILS = "Mario Kart Wii";
	PRESENCE->STATE = "Playing Mario Kart Wii";
	PRESENCE->START = DELTA_TIME(NULL);
}

static void DISCORD_SHUTDOWN(DISCORD_EVENT_HANDLERS* HANDLERS)
{
	free(HANDLERS);
}
