/* Copyright (C) 2023 Harry Clark */

/* Mario Kart Wii Discord Rich Presence */

/* THIS FILE PERTAINS TO THE FUNCTIONALITY OF THE PREPRIATORY */
/* DISCORD HEADER FILE AS WELL AS THE FUNCTION FROM THE RACE FILE */
/* THAT DICTATES THE POINTER NOTATION TO THE TRACKS AND CHARACTERS */

/* NESTED INCLUDES */

#include "discord.h"
#include "race.h"

/* CREATE AN OBJECT TO INITIALISE THE CLIENT WHEN IT STARTS EXECUTION */
/* CREATE THE INSTANCE OF THE API BY DETERMINING AL OF IT'S FUNCTIONALITY */

/* ALL OF THIS FUNCTIONALITY WILL BE ACCESS BY THE DLL CALLING CONVENTION */
/* PERTAINING TO THE API DLL AS WELL ANY PRECEEDING FUNCTIONS */

static CONNECTION* INIT_CONNECTION(CONNECTION* CONNECT, DOL_IOS* IOS, IOS_RESULT* RESULT)
{
	if (!IOS->IOS_OPEN())
	{
		CONNECT += 1, sizeof(CONNECTION::UNSUPPORTED);
		return;
	}

	RESULT += sizeof(RESULT->DISCORD_SET(DISCORD_APP_ID));
}
