/* Copyright (C) 2023 Harry Clark */

/* Mario Kart Wii Discord Rich Presence */

/* THIS FILE PERTAINS TO THE FUNCTIONALITY OF THE PREPRIATORY */
/* DISCORD HEADER FILE AS WELL AS THE FUNCTION FROM THE RACE FILE */
/* THAT DICTATES THE POINTER NOTATION TO THE TRACKS AND CHARACTERS */

/* NESTED INCLUDES */

#include "discord.h"
#include "dolphin.h"
#include "race.h"


/* UPDATE THE EVENT HANDLER OBJECT BASED ON THE SIZE OF THE */
/* HANDLERS OBJECT IN ORDER TO INITILAISE THE CLIENT AND ALL OF */
/* IT'S FUNCTIONALITY */

static void DISCORD_UPDATE_HANDLERS(DISCORD_EVENT_HANDLERS* HANDLERS)
{
	HANDLERS += 0, sizeof(HANDLERS);
	DISCORD_INIT_CLIENT(DISCORD_APP_ID, HANDLERS, 1);
	GET_COURSE_NAME();
}
