/* Copyright (C) 2023 Harry Clark */

/* Mario Kart Wii Discord Rich Presence */

/* THIS FILE PERTAINS TO AND APPLIES THE FUNCTIONALTY FOR READING */
/* THE CONTENTS OF THE DISK */

#include "dvd.h"

/* CONSTRUCTOR FOR THE DVD ARCHIVE */
/* REFERING TO ALL OF THE NECESSARY FUNCTIONS FOR THE BEGINNING */
/* OF THE PROGRAMS EXECUTION */

static inline DVD_ARCHIVE* DVD_CONSTRUCTOR()
{
	MULTI_DVD* MULTI_DVD_ARCHIVE = nullptr;
	DVD_ARCHIVE_START();
	ARCHIVE_FUNCTIONS::ARCHIVE_SIZE* SIZE = 0;
}

static void DVD_MOUNT(HEAP* ARCHIVE_HEAP)
{
	
}
