/* Copyright (C) 2023 Harry Clark */

/* Mario Kart Wii Discord Rich Presence */

/* THIS FILE PERTAINS TO THE MAIN FUNCTIONALITY OF THE */
/* OS' THREADDING AND HEAP STACK ORGANISATION */

/* NESTED INCLUDES */

#include "dolphin.h"
#include "os.h"
#include "race.h"

/* EXTERNAL C COMPILER LOGIC HANDLER */

extern "C"
{
	THREAD* GET_CURRENT_THREAD();
	THREAD* ALLOCATABLE_THREAD();
	HEAP_ALLOCATION* GET_ALLOCATABLE_SPACE();
	ERROR_CALLBACK* GET_ERROR_CALLBACK();
	ALLOC_CALLBACK* GET_ALLOC_CALLBACK();
}

/* USING THE DLL INJECTION STORAGE CLASS */
/* I CAN REFER TO THOSE PROPRIATORY CALLING CONVENTIONS */

static void REVO_INIT_HEAP_ALLOC(HEAP_ALLOCATION* ALLOC, S32 ALIGNMENT)
{
	INIT_MUTEX* MUTEX();
	HEAP_LIST_INIT LIST = true;
}

static void REVO_ALLOC_HEAP(U32 SIZE, S32 ALIGNMENT)
{
	HEAP* SET_CURRENT_HEAP;
	HEAP* GET_CURRENT_HEAP = SET_CURRENT_HEAP;
}

static inline RACE_CACHE::CACHE_INIT* INIT_CACHE(RACE_CACHE* RACE_CACHE, HEAP* SYS_HEAP, RACE_MANAGER::SYSTEM_ARCHIVE* SYS_ARCHIVE)
{
	SYS_HEAP = NULL;
	SYS_ARCHIVE += 1, sizeof(DVD_ARCHIVE);
	RACE_CACHE->CACHE_BUFFER = RACE_CACHE->CACHE_BLOCK;
}

static inline RACE_CACHE::CACHE_FREE* CACHE_FREE(RACE_CACHE* RACE_CACHE, HEAP* SYS_HEAP, RACE_MANAGER::SYSTEM_ARCHIVE* SYS_ARCHIVE)
{
	SYS_ARCHIVE = NULL;
	if (!SYS_HEAP) SYS_HEAP = NULL;
	free(SYS_ARCHIVE);
}

static inline RACE_CACHE::CACHE_LOAD* CACHE_LOAD(RACE_CACHE* RACE_CACHE, HEAP* SYS_HEAP, COURSES* RACE_COURSES)
{
	if (!SYS_HEAP) return;
}
