/* Copyright (C) 2023 Harry Clark */

/* Mario Kart Wii DIscord Rich Presence */

/* THIS FILE PERTAINS TO THE MAIN FUNCTIONALITY OF THE */
/* OS' THREADDING AND HEAP STACK ORGANISATION */

/* NESTED INCLUDES */

#include "os.h"
#include "dolphin.h"

/* EXTERNAL C COMPILER LOGIC HANDLER */

extern "C"
{
	THREAD* GET_CURRENT_THREAD();
	HEAP_ALLOCATION::ALLOC_HEAP* GET_ALLOCATABLE_SPACE();
	ERROR_CALLBACK* GET_ERROR_CALLBACK();
	ALLOC_CALLBACK* GET_ALLOC_CALLBACK();
}

void REVO_INIT_HEAP_ALLOC(HEAP_ALLOCATION* ALLOC, S32 ALIGNMENT)
{
	INIT_MUTEX* MUTEX();
	HEAP_LIST_INIT LIST = true;
};
