/* Copyright (C) 2023 Harry Clark */

/* Mario Kart Wii Discord Rich Presence */

/* THIS FILE PERTAINS TO THE MAIN FUNCTIONALITY */
/* FOR ACCESSING THE MEMORY ADDRESS OF THE RACE TRACKS */
/* AND THE CHARACTERS */

/* THIS INFORMATION WILL BE PARSED THROUGH THE API TO */
/* TO POINT TOWARDS WHICH TRACK AND CHARACTER THE USER */
/* IS USING */

/* NESTED INCLUDES */

#include "discord.h"
#include "dolphin.h"
#include "race.h"

/* LOAD THE DESIGNATED COURSES ACCORDING TO THE MEMORY ADDRESS */
/* OF THE COURSE SLOT IN RELATION TO THE SIZE OF THE COURSE NAME OBJECT */

/* THIS IS ASSUMING IF THIS ISN'T ALREADY WITHIN THE SCENE ARCHIVE HEAP */

static inline RACE_MANAGER::LOAD_COURSE* LOAD_COURSE(void)
{
	if(!RACE_MANAGER::SCENE_ARCHIVE)
	{
		RACE_MANAGER::RACE_FILENAME* FILE;
		FILE += FILENAME(&COURSE_ID_SLOT, sizeof(COURSE_NAME));

		return;
	}
};

/* GET THE COURSE NAME BASED ON A SWITCH CASE METHOD */
/* THIS WILL TAKE INTO ACCOUNT THE HEX VALUE OF THE COURSE FROM THE */
/* DESIGNATED ENUM IN THE HEADER FILE AND CALL BACK TO THE API */

static inline void GET_COURSE_NAME(RACE_MANAGER::RACE_INDEX INDEX, DISCORD_RICH_PRESENCE* PRESENCE)
{
	switch (INDEX)
	{
	case COURSES::LUIGI_CIRCUIT:
		PRESENCE->LARGE_IMAGE_KEY = "Luigi Circuit";
		PRESENCE->LARGE_IMAGE_TEXT = "Going for Gold";
			break;

	case COURSES::MOO_MOO_MEADOWS:
		PRESENCE->LARGE_IMAGE_KEY = "Moo Moo Meadows";
		PRESENCE->LARGE_IMAGE_TEXT = "Avoiding Cows";
		break;

	case COURSES::MUSHROOM_GORGE:
		PRESENCE->LARGE_IMAGE_KEY = "Mushroom Gorge";
		PRESENCE->LARGE_IMAGE_TEXT = "Bouncing on Mushrooms";
		break;

	case COURSES::TOADS_FACTORY:
		PRESENCE->LARGE_IMAGE_KEY = "Toad's Factory";
		PRESENCE->LARGE_IMAGE_TEXT = "Disrupting the production of goods";
		break;

		default:
			LOAD_COURSE();
			break;
	}
}
