/* Copyright (C) 2023 Harry Clark */

/* Mario Kart Wii Discord Rich Presence */

/* THIS FILE PERTAINS TO THE MAIN FUNCTIONALITY */
/* FOR ACCESSING THE MEMORY ADDRESS OF THE RACE TRACKS */
/* AND THE CHARACTERS */

/* THIS INFORMATION WILL BE PARSED THROUGH THE API TO */
/* TO POINT TOWARDS WHICH TRACK AND CHARACTER THE USER */
/* IS USING */

#include "race.h"

static inline RACE_MANAGER::LOAD_COURSE* LOAD_COURSE(void)
{
	if(!RACE_MANAGER::SCENE_ARCHIVE)
	{
		RACE_MANAGER::RACE_FILENAME* FILE;
		FILE += FILENAME(&COURSE_ID_SLOT, sizeof(COURSE_NAME));
	}
};

/* GET THE COURSE NAME BASED ON A SWITCH CASE METHOD */
/* THIS WILL TAE INT */

static inline void GET_COURSE_NAME(RACE_MANAGER::RACE_INDEX INDEX)
{
	switch (INDEX)
	{
	    case 0x0:
	}
}
