/* Copyright (C) 2023 Harry Clark */

/* Mario Kart Wii Discord Rich Presence */

/* THIS FILE PERTAINS TO THE MAIN FUNCTIONALITY */
/* FOR ACCESSING THE MEMORY ADDRESS OF THE RACE TRACKS */
/* AND THE CHARACTERS */

/* THIS INFORMATION WILL BE PARSED THROUGH THE API TO */
/* TO POINT TOWARDS WHICH TRACK AND CHARACTER THE USER */
/* IS USING */

#include "race.h"

static inline RACE_MANAGER::LOAD_COURSE* LOAD_COURSE(void)
{
	if(!RACE_MANAGER::SCENE_ARCHIVE)
	{
		RACE_MANAGER::RACE_FILENAME* FILE;
		FILE += FILENAME(sizeof(COURSE_NAME));
	}
};

/* INITIALISE THE GLOBAL HEAP METHOD FOR LOADING THE */
/* RESPECTIVE GAME SCENE IN CORRESPONDENCE WITH THE HEAP */

static void INIT_GLOBAL(UNK* HEAP_SIZE, HEAP* HEAP)
{

}

/* FREE ANY REMAINING OR SUBSEQUENT MEMORY FROM THE HEAP */

static void FREE_GLOBAL()
{
	free(FREE_GLOBAL);
}
